############################
## CHANGE THESE
############################

baseURL: "https://JulienPeloton.github.io/fink-website-rubin"
title: fink-website-rubin

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
