############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: News
  url: /post/
  weight: 20
- name: Publications
  url: /papers/
  weight: 30
- name: Joining
  url: /joining/
  weight: 40
- name: About
  url: /about/
  weight: 50
