############################
## Author
############################

author:
  name: 
  image: Fink_PrimaryLogo_WEB.png
  greeting: 
  icon: 

############################
## Links
############################

# <icon image name>-<hover display>
links:
  #- website-Science Portal: https://fink-portal.org
  - link-Documentation: https://fink-broker.readthedocs.io/en/latest
  - github-Github: https://github.com/astrolabsoftware
  - linkedin-Linkedin: https://www.linkedin.com/in/fink-broker-72b92134b/ 
  - email-contact: mailto:contact@fink-broker.org 


###############################
## OpenGraph & Twitter Cards
###############################

title: Fink broker
description: "Fink Broker collaboration website"
image: Fink_PrimaryLogo_WEB.png
